name: Test

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"
    tags-ignore:
      - "*"

permissions:
  contents: write

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:

# setup    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.3
    - name: Prepare publishment
      run: ./scripts/prepare.sh

# test
    - name: Test
      run: ./scripts/test.sh
