name: Test and Deploy

on: [push, pull_request]  

permissions:
  contents: write

jobs:

  TestAndDeploy:
    runs-on: ubuntu-latest
    steps:

# setup    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.3
    - name: Prepare publishment
      run: ./scripts/prepare.sh

# test
    - name: Test
      run: ./scripts/test.sh

# goreleaser:

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# publish:

    - name: Publish NPM
      uses: JS-DevTools/npm-publish@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: npm/package.json
